import {
  Dessert1,
  Dessert2,
  Dessert3,
  Dessert4,
  Dessert5,
  Dessert6,
  Drinks1,
  Drinks2,
  Drinks3,
  Drinks4,
  Drinks5,
  Drinks6,
  Salad1,
  Salad2,
  Salad3,
  Salad4,
  Salad5,
  Salad6,
  Soup1,
  Soup2,
  Soup3,
  Soup4,
  Soup5,
  Soup6,
  Spaghetti1,
  Spaghetti2,
  Spaghetti3,
  Spaghetti4,
  Spaghetti5,
  Spaghetti6,
  Starter1,
  Starter2,
  Starter3,
  Starter4,
  Starter5,
  Starter6,
} from "../../assets/menu/index";

const menuData = [
  {
    category: "Starter",
    name: "Caprese Starter",
    imageUrl: Starter1,
    price: "10.30",
    liked: false,
  },
  {
    category: "Starter",
    name: "Israeli Starter",
    imageUrl: Starter2,
    price: "12.30",
    liked: false,
  },
  {
    category: "Starter",
    name: "Roll Ball Starter",
    imageUrl: Starter3,
    price: "19.39",
    liked: false,
  },
  {
    category: "Starter",
    name: "Organic Mix Starter",
    imageUrl: Starter4,
    price: "60.30",
    liked: false,
  },
  {
    category: "Starter",
    name: "Quinoa Starter",
    imageUrl: Starter5,
    price: "21.10",
    liked: false,
  },
  {
    category: "Starter",
    name: "Asparagus Starter",
    imageUrl: Starter6,
    price: "41.10",
    liked: false,
  },
  {
    category: "Salad",
    name: "Asian Salad",
    imageUrl: Salad1,
    price: "20.40",
    liked: false,
  },
  {
    category: "Salad",
    name: "Spinach Salad",
    imageUrl: Salad2,
    price: "17.10",
    liked: false,
  },
  {
    category: "Salad",
    name: "Mexican Salad",
    imageUrl: Salad3,
    price: "11.47",
    liked: false,
  },
  {
    category: "Salad",
    name: "Quinoa Salad",
    imageUrl: Salad4,
    price: "91.30",
    liked: false,
  },
  {
    category: "Salad",
    name: "Tabbouleh Salad",
    imageUrl: Salad5,
    price: "56.25",
    liked: false,
  },
  {
    category: "Salad",
    name: "LentilSalad",
    imageUrl: Salad6,
    price: "31.91",
    liked: false,
  },
  {
    category: "Dessert",
    name: "Pantua Dessert",
    imageUrl: Dessert1,
    price: "60.50",
    liked: false,
  },
  {
    category: "Dessert",
    name: "Panna Dessert",
    imageUrl: Dessert2,
    price: "32.20",
    liked: false,
  },
  {
    category: "Dessert",
    name: "Pecan Pie",
    imageUrl: Dessert3,
    price: "41.97",
    liked: false,
  },
  {
    category: "Dessert",
    name: "Fruit Dessert",
    imageUrl: Dessert4,
    price: "19.20",
    liked: false,
  },
  {
    category: "Dessert",
    name: "Pineapple Dessert",
    imageUrl: Dessert5,
    price: "21.10",
    liked: false,
  },
  {
    category: "Dessert",
    name: "Chocolate Dessert",
    imageUrl: Dessert6,
    price: "41.10",
    liked: false,
  },
  {
    category: "Soup",
    name: "Butternut Soup",
    imageUrl: Soup1,
    price: "10.30",
    liked: false,
  },
  {
    category: "Soup",
    name: "Italian Mix Soup",
    imageUrl: Soup2,
    price: "12.30",
    liked: false,
  },
  {
    category: "Soup",
    name: "Hot Pasta Soup",
    imageUrl: Soup3,
    price: "19.39",
    liked: false,
  },
  {
    category: "Soup",
    name: "Miso Soup",
    imageUrl: Soup4,
    price: "60.30",
    liked: false,
  },
  {
    category: "Soup",
    name: "Thai Soup",
    imageUrl: Soup5,
    price: "69.55",
    liked: false,
  },
  {
    category: "Soup",
    name: "Tomato Soup",
    imageUrl: Soup6,
    price: "21.31",
    liked: false,
  },
  {
    category: "Spaghetti",
    name: "Mixed Spaghetti",
    imageUrl: Spaghetti1,
    price: "10.30",
    liked: false,
  },
  {
    category: "Spaghetti",
    name: "Spicy Spaghetti",
    imageUrl: Spaghetti2,
    price: "12.30",
    liked: false,
  },
  {
    category: "Spaghetti",
    name: "Creamy Spaghetti",
    imageUrl: Spaghetti3,
    price: "19.39",
    liked: false,
  },
  {
    category: "Spaghetti",
    name: "Simple Spaghetti",
    imageUrl: Spaghetti4,
    price: "60.30",
    liked: false,
  },
  {
    category: "Spaghetti",
    name: "Cheesy Spaghetti",
    imageUrl: Spaghetti5,
    price: "21.10",
    liked: false,
  },
  {
    category: "Spaghetti",
    name: "Roasted Spaghetti",
    imageUrl: Spaghetti6,
    price: "41.10",
    liked: false,
  },
  {
    category: "Drinks",
    name: "Saffron Shake",
    imageUrl: Drinks1,
    price: "10.30",
    liked: false,
  },
  {
    category: "Drinks",
    name: "Orange Juice",
    imageUrl: Drinks2,
    price: "12.30",
    liked: false,
  },
  {
    category: "Drinks",
    name: "Strawberry Juice",
    imageUrl: Drinks3,
    price: "19.39",
    liked: false,
  },
  {
    category: "Drinks",
    name: "Avocado Smoothie",
    imageUrl: Drinks4,
    price: "60.30",
    liked: false,
  },
  {
    category: "Drinks",
    name: "Malted Drink",
    imageUrl: Drinks5,
    price: "21.10",
    liked: false,
  },
  {
    category: "Drinks",
    name: "Special Juice",
    imageUrl: Drinks6,
    price: "41.10",
    liked: false,
  },
];

export default menuData;
